// Full Chaat Chaska menu - used as the fallback/seed.
// When Supabase is configured the live data overrides this.
// Each category has a Hindi-styled title + English subtitle.

export const MENU = [
  {
    id: "chaat",
    title: "Chaat Ke Chaske",
    subtitle: "The signature chaats",
    accent: "chili",
    items: [
      { name: "Pani Puri (Aloo Masala)", price: 7 },
      { name: "Pani Puri (Hot Ragda)", price: 8 },
      { name: "Dahi Puri", price: 10 },
      { name: "Sev Puri", price: 9 },
      { name: "Cheese Sev Puri", price: 11 },
      { name: "Sukha Bhel Puri", price: 8 },
      { name: "Gila Bhel Puri", price: 9 },
      { name: "Masala Puri (Dry)", price: 8 },
      { name: "Masala Puri (Gravy)", price: 9 },
      { name: "Papdi Chaat", price: 8 },
      { name: "Dahi Bhalla", price: 9 },
      { name: "Dahi Bhalla Papdi Chaat", price: 10 },
      { name: "Pineapple Dahi Bhalla", price: 11 },
      { name: "Dahi Samosa", price: 8 },
      { name: "Ragda Samosa", price: 8 },
      { name: "Ragda Dahi Samosa", price: 9 },
      { name: "Chole Samosa", price: 9 },
      { name: "Chole Dahi Samosa", price: 10 },
      { name: "Dal Kachori", price: 3 },
      { name: "Onion Kachori", price: 4 },
      { name: "Dahi Kachori", price: 8 },
      { name: "Raj Kachori", price: 12 },
      { name: "Aloo Tikki Chaat", price: 8 },
      { name: "Dahi Aloo Tikki Chaat", price: 9 },
      { name: "Dabeli", price: 5 },
      { name: "Katoori Chaat", price: 15 },
      { name: "Palak Chaat", price: 10 },
      { name: "Chana Chaat", price: 8 },
      { name: "Combo Chaat Platter", price: 20 },
    ],
  },
  {
    id: "breakfast",
    title: "Nasha Nashte Ka",
    subtitle: "Breakfast favourites",
    accent: "saffron",
    items: [
      { name: "Chole Bhatura", price: 14 },
      { name: "Puri Bhaji", price: 8.5 },
      { name: "Poha", price: 7 },
      { name: "Upma", price: 8 },
      { name: "Halwa Puri", price: 11 },
      { name: "Halwa Bhatura", price: 13 },
      { name: "Chole Puri", price: 10 },
      { name: "Paneer Bhurji & Bread", price: 12 },
      { name: "Paneer Bhurji & Chapati", price: 14 },
      { name: "Bread Butter Jam", price: 5 },
      { name: "Extra Bhatura", price: 5 },
      { name: "Chapati", price: 1.5 },
    ],
  },
  {
    id: "tawa",
    title: "Bombay Tawa Special",
    subtitle: "Sizzling off the griddle",
    accent: "chili",
    items: [
      { name: "Butter Pav Bhaji", price: 12 },
      { name: "Cheese Pav Bhaji", price: 15 },
      { name: "Paneer Pav Bhaji", price: 14 },
      { name: "Masala Pav", price: 8.5 },
      { name: "Extra Pav", price: 2 },
      { name: "Tawa Pulao", price: 13 },
      { name: "Tawa Paneer Pulao", price: 15 },
    ],
  },
  {
    id: "paratha",
    title: "Paratha's",
    subtitle: "Stuffed & griddled",
    accent: "saffron",
    items: [
      { name: "Aloo Paratha", price: 7.5 },
      { name: "Aloo Cheese Paratha", price: 9 },
      { name: "Cheese Paratha", price: 10 },
      { name: "Paneer Paratha", price: 10 },
      { name: "Mathi Paratha", price: 7.5 },
      { name: "Gobi Paratha", price: 7.5 },
      { name: "Onion Paratha", price: 7.5 },
      { name: "Mooli Paratha", price: 7.5 },
      { name: "Aloo Onion Paratha", price: 9 },
      { name: "Aloo Onion Cheese Paratha", price: 12 },
      { name: "Chaat Chaska Spc. Paratha", price: 15 },
    ],
  },
  {
    id: "dosa",
    title: "Dose Ki Dukan",
    subtitle: "South Indian classics",
    accent: "leaf",
    items: [
      { name: "Sada Dosa", price: 7 },
      { name: "Sada Cheese Dosa", price: 9 },
      { name: "Masala Dosa", price: 10 },
      { name: "Masala Cheese Dosa", price: 12 },
      { name: "Rava Sada Dosa", price: 11 },
      { name: "Rava Sada Cheese Dosa", price: 13 },
      { name: "Rava Masala Dosa", price: 14 },
      { name: "Rava Cheese Masala Dosa", price: 15 },
      { name: "Rava Onion Sada Dosa", price: 13 },
      { name: "Rava Onion Masala Dosa", price: 15 },
      { name: "Paneer Sada Dosa", price: 12 },
      { name: "Paneer Masala Dosa", price: 13 },
      { name: "Mysore Sada Dosa", price: 10 },
      { name: "Mysore Sada Cheese Dosa", price: 12 },
      { name: "Mysore Masala Dosa", price: 13 },
      { name: "Mysore Masala Cheese Dosa", price: 15 },
      { name: "Maharaja Masala Dosa", price: 15 },
      { name: "Hara-Bhara Masala Dosa", price: 15 },
    ],
  },
  {
    id: "chinese",
    title: "Chaska Chinese Kitchen",
    subtitle: "Indo-Chinese fusion",
    accent: "chili",
    items: [
      { name: "Veg Manchurian", price: 13 },
      { name: "Gobi Manchurian", price: 13 },
      { name: "Paneer Manchurian", price: 16 },
      { name: "Paneer Chilli", price: 16 },
      { name: "Veg Noodles", price: 13 },
      { name: "Veg Fried Rice", price: 16 },
    ],
  },
  {
    id: "uttapam",
    title: "Uttapam",
    subtitle: "Soft & savoury pancakes",
    accent: "leaf",
    items: [
      { name: "Plain Uttapam", price: 7 },
      { name: "Plain Cheese Uttapam", price: 9 },
      { name: "Onion Uttapam", price: 8 },
      { name: "Onion Cheese Uttapam", price: 10 },
      { name: "Onion Tomato Uttapam", price: 9 },
      { name: "Onion Tomato Cheese Uttapam", price: 11 },
      { name: "Chaat Chaska Spicy Uttapam", price: 16 },
      { name: "Hot Garlic Mexican Uttapam", price: 15 },
    ],
  },
  {
    id: "vadapav",
    title: "Vada Pav",
    subtitle: "Mumbai's favourite",
    accent: "saffron",
    items: [
      { name: "Chaat Chaska Vada Pav", price: 9 },
      { name: "Vada Pav", price: 5 },
      { name: "Masala Pav", price: 8 },
      { name: "Schezwan Vada Pav", price: 7 },
      { name: "Grill Vada Pav", price: 6 },
      { name: "Samosa Pav", price: 6 },
    ],
  },
  {
    id: "pakora",
    title: "Pakora",
    subtitle: "Crispy fritters",
    accent: "chili",
    items: [
      { name: "Chaat Chaska Bread Pakora", price: 6 },
      { name: "Bread Pakora", price: 4 },
      { name: "Onion Pakora", price: 8 },
      { name: "Potato Pakora", price: 7 },
      { name: "Mix Pakora", price: 8 },
      { name: "Paneer Pakora", price: 4 },
      { name: "Chilli Pakora", price: 3 },
      { name: "Pakora Platter", price: 18 },
    ],
  },
  {
    id: "thali",
    title: "Zaikedar Thali",
    subtitle: "Daily home-style platters",
    accent: "leaf",
    items: [
      { name: "Friday Thali (Jeera rice, Dal, paneer curry, Papad, Sweet, Salad & pickle)", price: 15 },
      { name: "Saturday Thali (Matar Pulao, Dal, Mix Veg, Papad, Sweet, Salad & pickle)", price: 15 },
      { name: "Sunday Thali (Ghee Rice, Dal, Aloo Palak, Papad, Sweet, Salad & pickle)", price: 15 },
      { name: "Monday Thali (Plain Rice, Dal, Aloo Gobi, Papad, Sweet, Salad & pickle)", price: 15 },
      { name: "Tuesday Thali (Plain Rice, Dal, Karela, Papad, Sweet, Salad & pickle)", price: 15 },
      { name: "Wednesday Thali (Plain Rice, Dal, Bhindi, Papad, Sweet, Salad & pickle)", price: 15 },
      { name: "Thursday Thali (Plain Rice, Dal, Aloo Matar, Papad, Sweet, Salad & pickle)", price: 15 },
      { name: "Rajma Chawal", price: 12 },
      { name: "Kadhi Chawal", price: 12 },
      { name: "Chole Chawal", price: 12 },
    ],
  },
  {
    id: "sandwich",
    title: "Sandwiches & Burgers",
    subtitle: "Toasted & grilled",
    accent: "saffron",
    items: [
      { name: "Veg Sandwich", price: 9 },
      { name: "Veg Cheese Grill Sandwich", price: 11 },
      { name: "Veg Paneer Grill Sandwich", price: 12 },
      { name: "Bombay Grill Sandwich", price: 10 },
      { name: "Chutney Cheese Sandwich", price: 7 },
      { name: "Chutney Cheese Grill Sandwich", price: 8 },
      { name: "Masala Cheese Sandwich", price: 10 },
      { name: "Masala Cheese Grill Sandwich", price: 12 },
      { name: "Chilli Cheese Grill Sandwich", price: 10 },
      { name: "Aloo Tikki Burger with Fries", price: 13 },
      { name: "Aloo Tikki Cheese Burger with Fries", price: 14 },
      { name: "Chaat Chaska Special Grill Sandwich", price: 16 },
    ],
  },
  {
    id: "kids",
    title: "Kids Special",
    subtitle: "Little ones' picks",
    accent: "turmeric",
    items: [
      { name: "Veg Cutlet", price: 2 },
      { name: "Nutella Bread Sandwich", price: 5 },
      { name: "French Fries", price: 6 },
      { name: "Cheesy Fries", price: 7 },
      { name: "Peri-Peri Fries", price: 7 },
    ],
  },
  {
    id: "sweets",
    title: "Man Se Mitha",
    subtitle: "Sweets & desserts",
    accent: "chili",
    items: [
      { name: "Gulab Jamun", price: 3.5 },
      { name: "Gulab Jamun with Ice Cream", price: 10 },
      { name: "Jalebi", price: 6 },
      { name: "Gujia", price: 3.5 },
      { name: "Kulfi Stick", price: 6.5 },
      { name: "Matka Kulfi", price: 9 },
      { name: "Fruit Salad with Ice Cream", price: 12 },
      { name: "Brownie with Ice Cream", price: 12 },
      { name: "Nutella Brownie", price: 14 },
    ],
  },
  {
    id: "falooda",
    title: "Falooda",
    subtitle: "Chilled layered treats",
    accent: "saffron",
    items: [
      { name: "Dry Fruit Falooda", price: 14 },
      { name: "Kesar Falooda", price: 13 },
      { name: "Fresh Fruit Falooda", price: 13 },
      { name: "Rose Falooda", price: 10 },
      { name: "Butter Scotch Falooda", price: 12 },
      { name: "Mango Falooda", price: 14 },
      { name: "Kulfi Falooda", price: 15 },
      { name: "Delhi Style Falooda", price: 16 },
      { name: "Pista Falooda", price: 15 },
    ],
  },
  {
    id: "shakes",
    title: "Milkshakes & Lassi",
    subtitle: "Thick, cold & creamy",
    accent: "leaf",
    items: [
      { name: "Banana Milkshake", price: 8 },
      { name: "Chocolate Milkshake", price: 11 },
      { name: "Strawberry Milkshake", price: 10 },
      { name: "Apple Milkshake", price: 10 },
      { name: "Vanilla Milkshake", price: 10 },
      { name: "Chikoo Milkshake", price: 10 },
      { name: "Oreo Milkshake", price: 12 },
      { name: "Dry-Fruit Milkshake", price: 12 },
      { name: "Kaju Milkshake", price: 12 },
      { name: "Mango Melody", price: 12 },
      { name: "Avocado Milkshake", price: 12 },
      { name: "Pista Milkshake", price: 10 },
      { name: "Kesar Milkshake", price: 12 },
      { name: "Sweet Lassi", price: 7 },
      { name: "Banana Lassi", price: 8 },
      { name: "Mango Lassi", price: 10 },
      { name: "Zafran Lassi", price: 10 },
    ],
  },
  {
    id: "cream",
    title: "Fresh Cream",
    subtitle: "Fruit & cream bowls",
    accent: "chili",
    items: [
      { name: "Mango Cream", price: 17 },
      { name: "Sitafal Cream", price: 17 },
      { name: "Strawberry Cream", price: 17 },
      { name: "Dry-Fruit Cream", price: 17 },
      { name: "Mix Fruit Cream", price: 19 },
    ],
  },
  {
    id: "juice",
    title: "Fresh Juice",
    subtitle: "Squeezed to order",
    accent: "saffron",
    items: [
      { name: "Sugarcane Juice", price: 13 },
      { name: "Watermelon Juice", price: 9 },
      { name: "Pineapple Juice", price: 12 },
      { name: "Orange Juice", price: 10 },
      { name: "Mango Juice", price: 10 },
      { name: "Strawberry Juice", price: 11 },
      { name: "Fresh Lime Water", price: 5 },
      { name: "Jal Jeera Water", price: 5 },
      { name: "Jeera Soda", price: 9 },
      { name: "Lime Soda", price: 8 },
      { name: "Lemon Mint Ginger", price: 10 },
    ],
  },
  {
    id: "mojito",
    title: "Mojito",
    subtitle: "Fizzy coolers",
    accent: "leaf",
    items: [
      { name: "Blueberry Mojito", price: 15 },
      { name: "Cranberry Mojito", price: 15 },
      { name: "Strawberry Mojito", price: 15 },
      { name: "Kala Khatta", price: 15 },
    ],
  },
  {
    id: "garam",
    title: "Garma Garam",
    subtitle: "Hot drinks & water",
    accent: "turmeric",
    items: [
      { name: "Fresh Milk Tea with Zafran", price: 1.5 },
      { name: "Coffee", price: 3 },
      { name: "Mineral Water (Small)", price: 1 },
      { name: "Mineral Water (Large)", price: 2 },
      { name: "Soft Drinks (Pepsi, Cola)", price: 3 },
    ],
  },
];

// A curated set of signature dishes for the homepage highlight grid.
export const SIGNATURE = [
  { id: "pani-puri", name: "Pani Puri", desc: "Crisp puris, spiced water, a burst in every bite.", price: 7, tag: "Most loved", img: "pani-puri.jpg", emoji: "🫗" },
  { id: "bhel-puri", name: "Bhel Puri", desc: "Puffed rice tossed with tangy chutneys & sev.", price: 8, tag: "Classic", img: "bhel-puri.jpg", emoji: "🥗" },
  { id: "sev-puri", name: "Sev Puri", desc: "Flat puris loaded with potato, onion & sev.", price: 9, tag: "Crunchy", img: "sev-puri.jpg", emoji: "🫓" },
  { id: "samosa", name: "Chole Samosa", desc: "Golden samosa drowned in spiced chickpeas.", price: 9, tag: "Comfort", img: "samosa.jpg", emoji: "🥟" },
  { id: "pav-bhaji", name: "Butter Pav Bhaji", desc: "Buttery mashed veg curry with soft pav.", price: 12, tag: "Hearty", img: "pav-bhaji.jpg", emoji: "🍛" },
  { id: "dosa", name: "Masala Dosa", desc: "Crisp golden crepe with potato masala.", price: 10, tag: "South special", img: "dosa.jpg", emoji: "🌯" },
  { id: "dahi-puri", name: "Dahi Puri", desc: "Cooling yogurt puris with sweet & spicy drizzle.", price: 10, tag: "Refreshing", img: "dahi-puri.jpg", emoji: "🥣" },
  { id: "falooda", name: "Delhi Style Falooda", desc: "Layered rose, vermicelli, kulfi & nuts.", price: 16, tag: "Dessert", img: "falooda.jpg", emoji: "🍨" },
];

export const TESTIMONIALS = [
  { name: "Aisha R.", role: "Madinat Zayed", rating: 5, text: "The pani puri here is unreal - exactly like the streets of Mumbai. We come back every weekend." },
  { name: "Rohan K.", role: "Musaffah", rating: 5, text: "Best dosa in Abu Dhabi, hands down. Crispy, huge, and the chutneys are next level." },
  { name: "Fatima A.", role: "Khalifa City", rating: 5, text: "Clean, friendly, and the pav bhaji tastes like home. The falooda is a must-try." },
  { name: "Vikram S.", role: "Al Wahda", rating: 5, text: "Authentic chaat with a modern touch. The combo platter is perfect for sharing." },
  { name: "Mariam H.", role: "Mussafah", rating: 5, text: "Honestly addicted to their sev puri and mango falooda. Service is quick and warm." },
  { name: "Deepak M.", role: "Madinat Zayed", rating: 5, text: "Everything is fresh and full of flavour. Feels like a proper Indian street food festival." },
];

// Gallery tiles for the Instagram-style grid + lightbox.
// Drop matching photos in /public/images/dishes/ - filenames 1.jpg, 2.jpg, etc.
// gracefully falls back to a branded emoji tile via DishImage.
export const GALLERY = [
  { id: "dish-1", name: "Delicious Chaat", emoji: "🫗", img: "dishes/1.jpg" },
  { id: "dish-2", name: "Spicy Treat", emoji: "🥗", img: "dishes/2.jpg" },
  { id: "dish-3", name: "Crunchy Bites", emoji: "🫓", img: "dishes/3.jpg" },
  { id: "dish-4", name: "Samosa Special", emoji: "🥟", img: "dishes/4.jpg" },
  { id: "dish-5", name: "Pav Bhaji Platter", emoji: "🍛", img: "dishes/5.jpg" },
  { id: "dish-6", name: "Crispy Dosa", emoji: "🌯", img: "dishes/6.jpg" },
  { id: "dish-7", name: "Creamy Dahi Puri", emoji: "🥣", img: "dishes/7.jpg" },
  { id: "dish-8", name: "Heavenly Falooda", emoji: "🍨", img: "dishes/8.jpg" },
  { id: "dish-9", name: "Street Food Delight", emoji: "🥨", img: "dishes/9.jpg" },
  { id: "dish-10", name: "Traditional Snack", emoji: "🍪", img: "dishes/10.jpg" },
  { id: "dish-11", name: "Masala Magic", emoji: "🥘", img: "dishes/11.jpg" },
  { id: "dish-12", name: "Sweet Finale", emoji: "🧁", img: "dishes/12.jpg" },
  { id: "dish-13", name: "Chef's Special", emoji: "🍲", img: "dishes/13.jpg" },
  { id: "dish-14", name: "Tasty Bite", emoji: "🍱", img: "dishes/14.jpg" },
  { id: "dish-15", name: "Evening Snack", emoji: "🍢", img: "dishes/15.jpg" },
];
